title: workshops.de Trainer Portal
description: ""
url: "https://trainer.workshops.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: workshops_de
github_username:  workshops-de
ga_property: "UA-39010393-10"
permalink: /artikel/:slug/
repository_url: "https://github.com/workshops-de/trainer.workshops.de"

include: ["_posts/banners"]

collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
  - scope:
      path: "_pages" # an empty string here means all files in the project
    values:
      layout: "page"

# Build settings
markdown: kramdown
sass:
  style: :compressed
  sass_dir: assets/css
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - .gitignore
  - nginx.conf
